# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9260fd4ef0dde5a7c558132c63f8a985ac4ca7bbd771f71b38c7b7362e80df0108c46454764b3074577ab4d0394ca889f795ffc65c07640d2e7409c4d4ebb225

test:
  secret_key_base: 3d78ad7fa4719f300a80f58888f584e6cb5e1290f30bf57d247db19e61947f58fb4605493de957724c405be92960d3b1ec5d0cdf715f56121e4fd20ebe53694c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
